section: screens
    master:
        halfDuplexCapsLock = false
        halfDuplexNumLock = false
        halfDuplexScrollLock = false
        xtestIsXineramaUnaware = false
        preserveFocus = false
        switchCorners = none
        switchCornerSize = 0
    node1:
        halfDuplexCapsLock = false
        halfDuplexNumLock = false
        halfDuplexScrollLock = false
        xtestIsXineramaUnaware = false
        preserveFocus = false
        switchCorners = none
        switchCornerSize = 0
    node2:
        halfDuplexCapsLock = false
        halfDuplexNumLock = false
        halfDuplexScrollLock = false
        xtestIsXineramaUnaware = false
        preserveFocus = false
        switchCorners = none
        switchCornerSize = 0
end

section: aliases
end

section: links
    # master (Laptop, Mitte): links=node1, rechts=node2
    master:
        left  = node1
        right = node2
    # node1 (Komposter 1, Links): rechts=master
    node1:
        right = master
    # node2 (Komposter 2, Rechts Hochkant): links=master
    node2:
        left  = master
end

section: options
    heartbeat        = 5000
    switchDelay      = 250
    switchDoubleTap  = false
    screenSaverSync  = true
    relativeMouseMoves = false
    clipboardSharing = true
    clipboardSharingSize = 32
end
